### ISSUE TITLE
Form contacto

### ISSUE THREAD

**Issue by Nidev-lab** [Augustoromera/Group-3-proyecto-final-Rolling-Code#6]
## Proceso

1. Ingrese a la pagina.
2. Llene el form de contacto.

## Resultado esperado

• Que no se puedan colocar numeros y signos en el nombre del usuario.

## Resultado actual

• Se permiten colocar numeros y signos.

## Captura

![image](https://github.com/Augustoromera/Group-3-proyecto-final-Rolling-Code/assets/53904695/76745ecc-5bea-41c6-b950-beba61c42ddc)
![image](https://github.com/Augustoromera/Group-3-proyecto-final-Rolling-Code/assets/53904695/6ecbb485-722f-4496-be2a-ec4627d4c8c2)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Augustoromera** [comment]
Implementación de validación de entrada para los campos de 'nombre' y 'apellido'. Se ha agregado una función handleChange que verifica si el valor ingresado en los campos de 'fitstName' y 'lastName' contiene caracteres alfabéticos y espacios en blanco, si no cumple con estos criterios, se ignora la entrada. Tambien se comprueba caracteres alfabéticos y la validación de campo vacío en un solo if para los campos de  'nombre' y 'apellido' para cu
<img width="632" alt="Captura form contacto 6" src="https://github.com/Augustoromera/Group-3-proyecto-final-Rolling-Code/assets/99555590/1ebcac5f-6b58-4d8f-8a70-ec463e338f76">
ando se envia el formulario, solo si cumple los requisitos en esos campos se completara la operación"
