### ISSUE TITLE
Errores de consola

### ISSUE THREAD

**Issue by Nidev-lab** [Augustoromera/Group-3-proyecto-final-Rolling-Code#7]
## Proceso

1. Ingrese a la pagina.
2. Me dirigí "Iniciar sesion".

## Resultado esperado

• No encontrar errores de consola.

## Resultado actual

• Se encuentran errores de consola.

## Captura

![image](https://github.com/Augustoromera/Group-3-proyecto-final-Rolling-Code/assets/53904695/1c93b3e6-3159-4b98-b360-60a37aeba370)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Augustoromera** [comment]
El el repositorio de backend se configuro 'https://rapiburger.netlify.app' como origen de CORS
<img width="386" alt="Captura issue errores de consola 7 - 2" src="https://github.com/Augustoromera/Group-3-proyecto-final-Rolling-Code/assets/99555590/3380971e-d192-42d6-88e7-601a181b13f4">
<img width="659" alt="Captura issue errores de consola 7" src="https://github.com/Augustoromera/Group-3-proyecto-final-Rolling-Code/assets/99555590/314bfc44-f64f-4b42-91b8-5167741fd51c">
