### ISSUE TITLE
Carrito

### ISSUE THREAD

**Issue by Nidev-lab** [Augustoromera/Group-3-proyecto-final-Rolling-Code#8]
## Proceso

1. Ingrese a la pagina.
2. Me loguee con un usuario.
3. Agregue uno pedidos al carrito.

## Resultado esperado

• Que al comprar no se muestre información por consola. 

## Resultado actual

• Al realizar la compra se muestra informacion por consola.

## Captura

![image](https://github.com/Augustoromera/Group-3-proyecto-final-Rolling-Code/assets/53904695/d24afe78-44b3-4cdf-a971-8d91e6bf1e08)
![image](https://github.com/Augustoromera/Group-3-proyecto-final-Rolling-Code/assets/53904695/7749b0db-8740-44e6-8c46-6d6f35131652)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by Augustoromera** [comment]
Se quito en Header.jsx de AppPedidos.jsx el mensaje en consola (la respuesta del servidor) cuando la operacion de compra tenia exito.
<img width="653" alt="Captura issue carrito 8" src="https://github.com/Augustoromera/Group-3-proyecto-final-Rolling-Code/assets/99555590/adea7539-53ad-4047-a5c2-d9aaaf5673be">
